siteConfig:
  title: Ayushman Bilas Thakur
  url: https://www.ayushmanbthakur.com

permalinks:
  post: /posts/:slug
  page: /:slug

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-sitemap
