siteConfig:
  title: Ayushman Bilas Thakur
  url: https://www.ayushmanbthakur.com
  email: ayushmanbilasthakur@gmail.com
  lang: en

permalinks:
  post: /posts/:slug
  page: /:slug

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-sitemap
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
      rss2Feed: true
      jsonFeed: true
